### PR TITLE
Fix flakiness of graceful termination test

### LINKED ISSUE #1236: Test Flake: TestServerGracefulTermination
Example: https://github.com/authzed/spicedb/actions/runs/4565810157/jobs/8057452447?pr=1235

```
panic: test timed out after 10m0s
running tests:
	TestServerGracefulTermination (10m0s)
```

### PR DESCRIPTION
**Pull request by josephschorr**
Appeared to be a race condition

Stress output:

```
$ stress ./server.test -test.run=TestServerGracefulTermination -test.cpu=2 -test.timeout=5s 5s: 951 runs so far, 0 failures
10s: 1992 runs so far, 0 failures
15s: 3071 runs so far, 0 failures
20s: 4134 runs so far, 0 failures
25s: 5159 runs so far, 0 failures
30s: 6215 runs so far, 0 failures
```

Fixes #1236

### CODE REVIEW

File: pkg/cmd/server/server_test.go [hunk 1]
```diff
@@ -32,18 +37,22 @@ func TestServerGracefulTermination(t *testing.T) {
 		WithNamespaceCacheConfig(CacheConfig{Enabled: true}),
 		WithDispatchCacheConfig(CacheConfig{Enabled: true}),
 		WithClusterDispatchCacheConfig(CacheConfig{Enabled: true}),
-		WithHTTPGateway(util.HTTPServerConfig{Enabled: true}),
-		WithDashboardAPI(util.HTTPServerConfig{Enabled: true}),
-		WithMetricsAPI(util.HTTPServerConfig{Enabled: true}),
+		WithHTTPGateway(util.HTTPServerConfig{Enabled: true, Address: fmt.Sprintf("localhost:%d", ports[0])}),
```
Comment (ecordell) [inline pkg/cmd/server/server_test.go:40]: you can just do `Address: ":"` and it should pick a free port

**Review by ecordell — APPROVED** [review]
