### PR TITLE
fix: use FAILED_PRECONDITION for recursion depth errors

### LINKED ISSUE #2728: Change recursion depth error to `FAILED_PRECONDITION`
From the [GRPC docs](https://grpc.io/docs/guides/status-codes/#full-list-of-status-codes):

> The operation was rejected because the system is not in a state required for the operation’s execution. For example, the directory to be deleted is non-empty, an rmdir operation is applied to a non-directory, etc. Service implementors can use the following guidelines to decide between FAILED_PRECONDITION, ABORTED, and UNAVAILABLE: (a) Use UNAVAILABLE if the client can retry just the failing call. (b) Use ABORTED if the client should retry at a higher level (e.g., when a client-specified test-and-set fails, indicating the client should restart a read-modify-write sequence). (c) Use FAILED_PRECONDITION if the client should not retry until the system state has been explicitly fixed. E.g., if an “rmdir” fails because the directory is non-empty, FAILED_PRECONDITION should be returned since the client should not retry unless the files are deleted from the directory.

We currently return a `RESOURCE_EXHAUSTED`, but we want to reserve `RESOURCE_EXHAUSTED` for operations that can safely be retried. A recursion depth error indicates a data cycle that requires the client to fix the cycle before the operation can be safely retried.

It seems as though `FAILED_PRECONDITION` is a better fit here.

### PR DESCRIPTION
**Pull request by tstirrat15**
Fixes #2728 

## Description
See #2728. We want to reserve `RESOURCE_EXHAUSTED` for things that can be safely retried, and a recursion depth error cannot generally be safely retried. The docs indicate that `FAILED_PRECONDITION` is more appropriate here.

## Changes
* Change recursion depth error to have a `ResourceExhausted` code
* Update tests
## Testing
Review.

### CODE REVIEW

**Comment by tstirrat15** [comment]
I've added an issue to that repo.

File: internal/services/shared/errors_test.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ func TestRewriteError(t *testing.T) {
 			config: &ConfigForErrors{
 				MaximumAPIDepth: 50,
 			},
-			expectedCode:     codes.ResourceExhausted,
+			expectedCode:     codes.FailedPrecondition,
 			expectedContains: "max depth exceeded: this usually indicates a recursive or too deep data dependency. See https://spicedb.dev/d/debug-max-depth",
```
Comment (miparnisari) [inline internal/services/shared/errors_test.go]:
```suggestion
			expectedContains: "max depth exceeded: this usually indicates a recursive or too deep data dependency. See " + sharederrors.MaxDepthErrorLink,
```

**Review by miparnisari — DISMISSED** [review]

**Review by miparnisari — APPROVED** [review]
