### PR TITLE
fix: segfault with datastore bootstrap files

### LINKED ISSUE #2783: Using `--datastore-bootstrap-files` with caveated relations results in SIGSEGV
### What platforms are affected?

windows, linux

### What architectures are affected?

amd64

### What SpiceDB version are you using?

v1.48.0

### What SpiceDB flags do you use?

1. --grpc-preshared-key=any
2. --datastore-bootstrap-files=/resources/schema.yml
3. --log-level=trace

### Steps to Reproduce

Start a container with spiceDB with a schema.yml file (--datastore-bootstrap-files=/resources/schema.yml) containing 
```
schema: |-
  
  definition user {}
  
  caveat mfa_match_multi(acceptable_amr list<string>, provided_amr list<string>) {
     size(acceptable_amr) == 0 || (size(provided_amr) > 0 && acceptable_amr.exists(x, x in provided_amr))
  }

  definition organization {
    relation mfa_guard: organization with mfa_match_multi
    relation check: user:*
      
    permission secured_access = mfa_guard->check
  }
  
relationships: |-
  organization:orga#mfa_guard@organization:orga[mfa_match_multi:{"acceptable_amr": ["mfa"]}]
```

(alternatively, use the file joined, that contains the same thing)

[schema.yml](https://github.com/user-attachments/files/24261337/schema.yml)

### Expected Result

The container starts and can be queryed with the caveated data available.

### Actual Result

the container fails to start.

full Startup logs : 
```
2025-12-19 17:06:52 {"level":"info","time":"2025-12-19T16:06:52Z","message":"using memory datastore engine"}
2025-12-19 17:06:52 {"level":"warn","time":"2025-12-19T16:06:52Z","message":"in-memory datastore is not persistent and not feasible to run in a high availability fashion"}
2025-12-19 17:06:52 {"level":"info","files":["/resources/schema.yml"],"time":"2025-12-19T16:06:52Z","message":"initializing datastore from bootstrap files"}
2025-12-19 17:06:53 {"level":"info","filePath":"/resources/schema.yml","definitionCount":2,"caveatDefinitionCount":1,"schemaDefinitionCount":3,"time":"2025-12-19T16:06:53Z","message":"adding schema definitions"}
2025-12-19 17:06:53 panic: runtime error: invalid memory address or nil pointer dereference
2025-12-19 17:06:53 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12ed54d]
2025-12-19 17:06:53 
2025-12-19 17:06:53 goroutine 1 [running]:
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/caveats/types.DecodeParameterType(0x0, 0xc000e705a0)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/caveats/types/encoding.go:34 +0x2d
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/caveats.ConvertContextToParameters(0x0, 0xc000e69020, 0xc000e68fc0, 0x1)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/caveats/parameters.go:52 +0x19b
2025-12-19 17:06:53 github.com/authzed/spicedb/internal/relationships.ValidateOneRelationship(0xc000e68f30, 0xc000e68ff0, 0x0, {0xc000b4ea00, 0x0, 0x0, {{{0xc000e3200d, 0x4}, {0xc000e32000, 0xc}, ...}, ...}}, ...)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/internal/relationships/validation.go:260 +0x92e
2025-12-19 17:06:53 github.com/authzed/spicedb/internal/relationships.ValidateRelationshipsForCreateOrTouch({0x3a63f30?, 0xc0002f2070?}, {0x7e3aaa013780?, 0xc000e703c0?}, 0x0, {0xc000934180, 0x1, 0x47fd19?})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/internal/relationships/validation.go:76 +0x14e
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/validationfile.PopulateFromFilesContents.func2.1({0x3a63f30, 0xc0002f2070}, {0x3a94bb8, 0xc000e703c0})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/validationfile/loader.go:211 +0x92
2025-12-19 17:06:53 github.com/authzed/spicedb/internal/datastore/memdb.(*memdbDatastore).ReadWriteTx(0xc0009f4630, {0x3a63f30, 0xc0002f2070}, 0xc000e70370, {0x0, 0x0, 0x35?})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/internal/datastore/memdb/memdb.go:195 +0x2f4
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/validationfile.PopulateFromFilesContents.func2({0xc000935280, 0x1, 0x1})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/validationfile/loader.go:210 +0x342
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/genutil/slicez.ForEachChunk[...].func1()
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/genutil/slicez/chunking.go:14 +0x1c
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/genutil/slicez.ForEachChunkUntil[...]-range1(...)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/genutil/slicez/chunking.go:28
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/genutil/slicez.ForEachChunkUntil[...].func1(...)
2025-12-19 17:06:53     /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.5.linux-amd64/src/slices/iter.go:109
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/genutil/slicez.ForEachChunkUntil[...]({0xc000935280?, 0x1, 0x1}, 0x140, 0xc000c050a8?)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/genutil/slicez/chunking.go:27 +0x196
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/genutil/slicez.ForEachChunk[...]({0xc000935280?, 0xc0002f2070?, 0xc000e70050?}, 0x0?, 0x0?)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/genutil/slicez/chunking.go:13 +0x36
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/validationfile.PopulateFromFilesContents({0x3a63f30, 0xc0002f2070}, {0x3a8ab80, 0xc0009f4630}, 0x0, 0xc000c05760)
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/validationfile/loader.go:201 +0xe47
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/validationfile.PopulateFromFiles({0x3a63f30, 0xc0002f2070}, {0x3a8ab80, 0xc0009f4630}, 0x0, {0xc00078e2c0, 0x1, 0x3fb999999999999a?})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/validationfile/loader.go:64 +0x1d3
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/cmd/datastore.NewDatastore({0x3a63888, 0x5b343c0}, {0xc000c07970, 0x3, 0x0?})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/cmd/datastore/datastore.go:426 +0x7a5
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/cmd/server.(*Config).Complete(0xc000b62d08, {0x3a63888, 0x5b343c0})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/cmd/server/server.go:243 +0x331
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/cmd.NewServeCommand.func1(0x0?, {0x0?, 0x0?, 0x0?})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/cmd/serve.go:242 +0x2d
2025-12-19 17:06:53 github.com/authzed/spicedb/pkg/cmd.NewServeCommand.PublishError.func2(0xc000b88308, {0xc000725f20?, 0x0?, 0x6?})
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/pkg/cmd/termination/termination.go:28 +0x33
2025-12-19 17:06:53 github.com/spf13/cobra.(*Command).execute(0xc000b88308, {0xc000725ec0, 0x6, 0x6})
2025-12-19 17:06:53     /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1015 +0xb02
2025-12-19 17:06:53 github.com/spf13/cobra.(*Command).ExecuteC(0xc000341808)
2025-12-19 17:06:53     /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1148 +0x465
2025-12-19 17:06:53 github.com/spf13/cobra.(*Command).Execute(0x7e3aa9c94a70?)
2025-12-19 17:06:53     /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.10.2/command.go:1071 +0x13
2025-12-19 17:06:53 main.main()
2025-12-19 17:06:53     /home/runner/work/spicedb/spicedb/cmd/spicedb/main.go:39 +0x1cf
```

__*Note*__ : starting the container with `serve-testing` and `--load-configs` does works. (although because of code configuration, I havn't yet tested if the data is present.)

### PR DESCRIPTION
**Pull request by tstirrat15**
Fixes #2783 

## Description
In #2315, we added support for different caveat typesets being handed to the startup process. Further down in the tree, if a typeset is missing, it will default to the default set, but we weren't doing that in the validationfile logic that supports `--datastore-bootstrap-files`.

This PR sets that default fairly high in the tree so that it's available for the validationfile logic.

## Note
Given that this default behavior isn't causing problems elsewhere in the tree, I'm not entirely sure that setting the default this high makes sense. It might be preferable to make the validationfile logic use a default if the typeset isn't provided.

## Changes
* Set default in `Complete()` so that it's available for the validationfile logic.
## Testing
Review. See that the repro steps in #2783 no longer repro.

### CODE REVIEW

File: pkg/cmd/server/server.go [hunk 1]
```diff
@@ -245,6 +246,9 @@ func (c *Config) Complete(ctx context.Context) (RunnableServer, error) {
 			// are at most the number of elements returned from a datastore query
 			datastorecfg.WithFilterMaximumIDCount(c.DispatchChunkSize),
 			datastorecfg.WithEnableRevisionHeartbeat(c.EnableRevisionHeartbeat),
+			// NOTE: this isn't something that you can meaningfully set from the outside, so we set the
+			// defaul there so that downstream references to the configuration can make use of it.
```
Comment (miparnisari) [inline pkg/cmd/server/server.go]: this comment doesn't make sense to me. if the caller can't set this, then why offer an option at all? just set the value in the constructor

also, can we write a test that reproduces the segfault?

Comment (tstirrat15) [reply pkg/cmd/server/server.go]: I realized it makes more sense to solve in the `datastore` file. I wrote a test that reproduces the segfault.
