### PR TITLE
Avoid logging with testing.T after test has finished

### LINKED ISSUE #394: e2e test error: Log in goroutine after TestNoNewEnemy has completed: no such process
When merging in the latest main changes (as of Jan 31  8:45am PT). I encountered the following error in the e2e test suite: 

```
2022-01-31T16:45:42.2426549Z     newenemy_test.go:343: 1643647542070212767 1643647542070212767.0000000039 -0.0000000039 1 1 3 3
2022-01-31T16:45:42.5098528Z     newenemy_test.go:343: 1643647542347004451 1643647542347004451.0000000037 -0.0000000037 1 1 3 3
2022-01-31T16:45:42.6102526Z === CONT  TestNoNewEnemy/protected_from_data_newenemy
2022-01-31T16:45:42.6102998Z     newenemy_test.go:231: spicedb is protected after 2 attempts
2022-01-31T16:45:42.6103560Z --- PASS: TestNoNewEnemy (80.27s)
2022-01-31T16:45:42.6103980Z     --- PASS: TestNoNewEnemy/protected_from_schema_newenemy (30.14s)
2022-01-31T16:45:42.6104444Z     --- PASS: TestNoNewEnemy/protected_from_data_newenemy (4.82s)
2022-01-31T16:45:42.6104687Z PASS
2022-01-31T16:45:42.6157997Z panic: Log in goroutine after TestNoNewEnemy has completed: no such process
2022-01-31T16:45:42.6158742Z 
2022-01-31T16:45:42.6158755Z 
2022-01-31T16:45:42.6158767Z 
2022-01-31T16:45:42.6159085Z goroutine 158 [running]:
2022-01-31T16:45:42.6159392Z testing.(*common).logDepth(0xc000106680, {0xc0002f0a98, 0x11}, 0x3)
2022-01-31T16:45:42.6159754Z 	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:779 +0x4c9
2022-01-31T16:45:42.6160020Z testing.(*common).log(...)
2022-01-31T16:45:42.6160316Z 	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:761
2022-01-31T16:45:42.6160620Z testing.(*common).Log(0x40ca07, {0xc0003fb8a0, 0xaf1be0, 0x1})
2022-01-31T16:45:42.6160936Z 	/opt/hostedtoolcache/go/1.17.6/x64/src/testing/testing.go:800 +0x45
2022-01-31T16:45:42.6161283Z github.com/authzed/spicedb/e2e.(*TLogger).Write(0xc00000e1b0, {0xc0001a6280, 0x10, 0x9})
2022-01-31T16:45:42.6161624Z 	/home/runner/work/spicedb/spicedb/e2e/util.go:17 +0xa6
2022-01-31T16:45:42.6161920Z fmt.Fprintln({0xd1d7a0, 0xc00000e1b0}, {0xc0003f37c0, 0x1, 0x1})
2022-01-31T16:45:42.6162248Z 	/opt/hostedtoolcache/go/1.17.6/x64/src/fmt/print.go:265 +0x75
2022-01-31T16:45:42.6162557Z github.com/authzed/spicedb/e2e.cleanupOnDone.func1()
2022-01-31T16:45:42.6162881Z 	/home/runner/work/spicedb/spicedb/e2e/run.go:55 +0x87
2022-01-31T16:45:42.6163164Z created by github.com/authzed/spicedb/e2e.cleanupOnDone
2022-01-31T16:45:42.6163476Z 	/home/runner/work/spicedb/spicedb/e2e/run.go:51 +0xa7
2022-01-31T16:45:42.6163788Z FAIL	github.com/authzed/spicedb/e2e/newenemy	80.288s
2022-01-31T16:45:42.6229755Z FAIL
2022-01-31T16:45:42.6269086Z ##[error]Process completed with exit code 1.
2022-01-31T16:45:42.6309006Z ##[group]Run actions/upload-artifact@v2
2022-01-31T16:45:42.6309229Z with:
2022-01-31T16:45:42.6309412Z   name: node-logs
2022-01-31T16:45:42.6309613Z   path: e2e/newenemy/*.log
2022-01-31T16:45:42.6309813Z   if-no-files-found: warn
``` 

The good news is this was a fast failure! Most of the previous failures were timeouts from a stalled test run.

### PR DESCRIPTION
**Pull request by ecordell**
To keep the test output consistent, several test helpers use a wrapped `t.Log` as a writer for subprocess output. The cleanup code for these run in a goroutine that listens for context cancellation, and may still be running after the test. This can lead to issues where the test suite passes, but the logs still show a panic.

This always writes cleanup messages to stderr instead, so that it doesn't matter if they run after the test is done.

Fixes #394

### CODE REVIEW

File: e2e/newenemy/newenemy_test.go [hunk 1]
```diff
@@ -128,6 +128,9 @@ func TestNoNewEnemy(t *testing.T) {
 	require.NoError(t, vulnerableSpiceDb.Start(ctx, tlog, "vulnerable",
 		"--datastore-tx-overlap-strategy=insecure"))
 	require.NoError(t, vulnerableSpiceDb.Connect(ctx, tlog))
+	t.Cleanup(func() {
+		require.NoError(t, vulnerableSpiceDb.Stop(tlog))
```
Comment (samkim) [inline e2e/newenemy/newenemy_test.go:132]: If one of the cleanup funcs fails the require check, does that prevent subsequent cleanup funcs from running?

File: e2e/run.go [hunk 2]
```diff
@@ -25,7 +26,7 @@ func GoRun(ctx context.Context, out, errOut io.Writer, args ...string) (int, err
 		return 0, err
 	}
 	go func() {
-		cleanupOnDone(ctx.Done(), cmd.Process.Pid, errOut)
+		cleanupOnDone(ctx.Done(), cmd.Process.Pid, os.Stderr)
```
Comment (samkim) [inline e2e/run.go:29]: Doesn't look like there are any other callers of `cleanupOnDone`. Could remove the param altogether and just use Stderr in the function itself

File: e2e/newenemy/newenemy_test.go (hunk 1 above)
Comment (ecordell) [reply e2e/newenemy/newenemy_test.go:132]: All of the registered cleanup funcs should run: https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/testing/testing.go;l=1019;drc=refs%2Ftags%2Fgo1.17.6;bpv=1;bpt=1

File: e2e/run.go (hunk 2 above)
Comment (ecordell) [reply e2e/run.go]: good catch, updated

**Review by samkim — APPROVED** [review]
LGTM
