### PR TITLE
datastore/postgres: switch to DB snapshots as primary component of revisions

### LINKED ISSUE #1130: Invalid permissions are returned when using fullyConsistent mode
Description: After writing relationships to SpiceDB, subsequent check permissionship calls in fullyConsistent mode (made within >5s after relationship write) are sporadically returning invalid PERMISSIONSHIP_NO_PERMISSION response.

Environment:
SpiceDB 1.16.1
Postgres 14.6
OPA 0.47.4

Relevant SpiceDB schema parts:
```
definition user {
      /** Service accounts linked to the user */
      relation service_accounts: service_account
}
    
definition service_account {
  /** This type represents service accounts (e.g. Personal Access Tokens) */
}

definition project {
  /** Project manager users */
  relation project_manager: user
  permission can_manage = project_manager +
                          project_manager->service_accounts
}
```

Reproduction flow:
1. We are creating a new `project` object in POST API endpoint and adding a `project_manager` relation between user issuing the call and created project object (using python client for SpiceDB).
2. After several seconds, we issue an GET or DELETE call to projects endpoint, using service_account linked to the user which created the project. These endpoints are guarded by Open Policy Agent sidecars, which are calling SpiceDB's REST API to check permissions for the caller. Calls are made with fullyConsistent policy.
3. We are seeing that some requests (around 1 failed requests per 500 retries of this flow) are failing due to PERMISSIONSHIP_NO_PERMISSION being received from spiceDB, although proper relations are in place in SpiceDB for the subject and requested resource.

Excerpts from logs:

1. `project` resource created with `project_manager` relationship:

SpiceDB logs:
```
{"level":"debug","module":"pgx","args":["project","63d91e29843ad90ac48de3ac","parent_workspace","workspace", "63d13bd6843ad90ac4877c07","...","",null,"project","63d91e29843ad90ac48de3ac","project_manager","user","YWRtaW5Ac2MtcHJvamVjdC5pbnRlbC5jb20","...","",null],"commandTag":"SU5TRVJUIDAgMg==","pid":856693,"sql":"INSERT INTO relation_tuple (namespace,object_id,relation,userset_namespace,userset_object_id,userset_relation,caveat_name,caveat_context) VALUES ($1,$2,$3,$4,$5,$6,$7,$8),($9,$10,$11,$12,$13,$14,$15,$16)","time":2.830403,"time":"2023-01-31T13:56:57Z","message":"Exec"}
```
Application logs:
```
2023-01-31 13:56:57,536 [INFO    ] [microservices.utils.spicedb:134]: SPICEDB Response written_at {
  token: "Gg0KCzE5MDgyLjE5MDgy"
}
 for call _write_relations with (<microservices.utils.spicedb.SpiceDB object at 0x7f73a1d8d850>,) and {'updates': [operation: OPERATION_CREATE
relationship {
  resource {
    object_type: "project"
    object_id: "63d91e29843ad90ac48de3ac"
  }
  relation: "parent_workspace"
  subject {
    object {
      object_type: "workspace"
      object_id: "63d13bd6843ad90ac4877c07"
    }
  }
}
, operation: OPERATION_CREATE
relationship {
  resource {
    object_type: "project"
    object_id: "63d91e29843ad90ac48de3ac"
  }
  relation: "project_manager"
  subject {
    object {
      object_type: "user"
      object_id: "YWRtaW5Ac2MtcHJvamVjdC5pbnRlbC5jb20"
    }
  }
}
]}
```

2. DELETE call is made after several seconds and fails with PERMISSIONSHIP_NO_PERMISSION
OPA logs:
```
{"decision-id":"47c29184-681b-408a-a9f2-8a48438e4fd9","level":"info","msg":"/policies/default/policy.rego:473: Checking delete_project permission for project object 63d91e29843ad90ac48de3ac and service_account subject NExEaFIzVmZtUjZUb3pma29tTHpmU1BzU1pDdFVDRHc","time":"2023-01-31T13:56:59Z"}
{"decision-id":"47c29184-681b-408a-a9f2-8a48438e4fd9","level":"info","msg":"/policies/default/policy.rego:496: Permission request {\"body\": {\"consistency\": {\"fullyConsistent\": true}, \"permission\": \"delete_project\", \"resource\": {\"objectId\": \"63d91e29843ad90ac48de3ac\", \"objectType\": \"project\"}, \"subject\": {\"object\": {\"objectId\": \"NExEaFIzVmZtUjZUb3pma29tTHpmU1BzU1pDdFVDRHc\", \"objectType\": \"service_account\"}}}, \"cache\": true, \"headers\": {\"Authorization\": \"Bearer N87TWAQpf5eP\", \"content-type\": \"application/json\"}, \"method\": \"POST\", \"url\": \"http://spice-db:8443/v1/permissions/check\"}","time":"2023-01-31T13:56:59Z"}
{"decision-id":"47c29184-681b-408a-a9f2-8a48438e4fd9","level":"info","msg":"/policies/default/policy.rego:498: Permission response {\"body\": {\"checkedAt\": {\"token\": \"Gg0KCzE5MDgzLjE5MDgy\"}, \"partialCaveatInfo\": null, \"permissionship\": \"PERMISSIONSHIP_NO_PERMISSION\"}, \"headers\": {\"content-type\": [\"application/json\"], \"date\": [\"Tue, 31 Jan 2023 13:56:59 GMT\"], \"grpc-metadata-content-type\": [\"application/grpc\"], \"grpc-metadata-io.spicedb.respmeta.requestid\": [\"c085c35cbbd46770bd79b85e8bdc5848\"], \"server\": [\"envoy\"], \"x-envoy-upstream-service-time\": [\"51\"]}, \"raw_body\": \"{\\\"checkedAt\\\":{\\\"token\\\":\\\"Gg0KCzE5MDgzLjE5MDgy\\\"},\\\"permissionship\\\":\\\"PERMISSIONSHIP_NO_PERMISSION\\\",\\\"partialCaveatInfo\\\":null}\", \"status\": \"200 OK\", \"status_code\": 200}","time":"2023-01-31T13:56:59Z"}
```

I've also compared v1/permissions/expand responses for this particular project at ZedTokens returned during POST and DELETE calls:

Expanded permissions on POST ZedToken:
```
{"expandedAt":{"token":"Gg0KCzE5MDgyLjE5MDgy"},"treeRoot":{"intermediate":{"operation":"OPERATION_UNION","children":[{"intermediate":{"operation":"OPERATION_UNION","children":[{"intermediate":{"operation":"OPERATION_UNION","children":[{"leaf":{"subjects":[{"object":{"objectType":"user","objectId":"YWRtaW5Ac2MtcHJvamVjdC5pbnRlbC5jb20"},"optionalRelation":""}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"project_manager"},{"intermediate":{"operation":"OPERATION_UNION","children":[{"leaf":{"subjects":[{"object":{"objectType":"service_account","objectId":"NExEaFIzVmZtUjZUb3pma29tTHpmU1BzU1pDdFVDRHc"},"optionalRelation":""}]},"expandedObject":{"objectType":"user","objectId":"YWRtaW5Ac2MtcHJvamVjdC5pbnRlbC5jb20"},"expandedRelation":"service_accounts"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"},{"intermediate":{"operation":"OPERATION_UNION","children":[{"intermediate":{"operation":"OPERATION_UNION","children":[{"leaf":{"subjects":[{"object":{"objectType":"user","objectId":"YWRtaW5Ac2MtcHJvamVjdC5pbnRlbC5jb20"},"optionalRelation":""}]},"expandedObject":{"objectType":"workspace","objectId":"63d13bd6843ad90ac4877c07"},"expandedRelation":"workspace_admin"}]},"expandedObject":{"objectType":"workspace","objectId":"63d13bd6843ad90ac4877c07"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"delete_project"}}
```

Expanded permissions on DELETE ZedToken:
```
{"expandedAt":{"token":"Gg0KCzE5MDgzLjE5MDgy"},"treeRoot":{"intermediate":{"operation":"OPERATION_UNION","children":[{"intermediate":{"operation":"OPERATION_UNION","children":[{"intermediate":{"operation":"OPERATION_UNION","children":[{"leaf":{"subjects":[]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"project_manager"},{"intermediate":{"operation":"OPERATION_UNION","children":[]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"},{"intermediate":{"operation":"OPERATION_UNION","children":[]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"can_manage"}]},"expandedObject":{"objectType":"project","objectId":"63d91e29843ad90ac48de3ac"},"expandedRelation":"delete_project"}}
```

Note that although ZedToken returned by DELETE call check is newer than one returned in POST endpoint, expanding permissions using newer token does not compute expected result.
I've checked relations in SpiceDB using both ZedTokens and results were the same, so it seems that issue is only in permission check computation.

Could you tell me if this behaviour should be expected when using fullyConsistent mode? 
It looks like after waiting several more seconds permissions are computed correctly, but I had an impression that these delays should not happen when full consistency mode is used.

### PR DESCRIPTION
**Pull request by jakedt**
Fixes #1130

### CODE REVIEW

File: internal/datastore/postgres/caveat.go [hunk 1]
```diff
@@ -53,7 +62,12 @@ func (r *pgReader) ReadCaveatByName(ctx context.Context, name string) (*core.Cav
 	if err != nil {
 		return nil, datastore.NoRevision, fmt.Errorf(errReadCaveat, err)
 	}
-	rev := postgresRevision{txID, noXmin}
+
+	if txID.Status != pgtype.Present {
```
Comment (josephschorr) [inline internal/datastore/postgres/caveat.go:66]: can we comment here on what this check means, exactly?

File: internal/datastore/postgres/postgres_test.go [hunk 2]
```diff
@@ -210,7 +219,7 @@ func GarbageCollectionTest(t *testing.T, ds datastore.Datastore) {
 	require.NoError(err)
 	require.Zero(removed.Relationships)
 	require.Equal(int64(1), removed.Transactions) // firstWrite
-	require.Zero(removed.Namespaces)
+	require.Equal(int64(2), removed.Namespaces)   // resource, user
```
Comment (josephschorr) [inline internal/datastore/postgres/postgres_test.go:222]: why did this change?

File: internal/datastore/postgres/revisions.go [hunk 3]
```diff
@@ -107,129 +121,95 @@ func (pgd *pgDatastore) RevisionFromString(revisionStr string) (datastore.Revisi
...
-			return datastore.NoRevision, fmt.Errorf(
-				errRevisionFormat,
-				errors.New("xmin component is negative"),
-			)
-		}
-		xmin = xid8{
-			Uint:   uint64(xminInt),
-			Status: pgtype.Present,
-		}
+	decoded := implv1.PostgresRevision{}
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions.go:129]: Probably worth documenting the format here

File: internal/datastore/postgres/snapshot.go [hunk 4]
```diff
@@ -0,0 +1,236 @@
...
+import (
+	"fmt"
+	"strconv"
+	"strings"
+
+	"github.com/jackc/pgtype"
+	"golang.org/x/exp/slices"
+)
+
+type pgSnapshot struct {
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:14]: Can we add some doc comments here on how this is represented, etc?

Comment (josephschorr) [reply internal/datastore/postgres/snapshot.go:14]: Particularly on the text format used

File: internal/datastore/postgres/snapshot.go [hunk 5]
```diff
@@ -0,0 +1,236 @@
...
+	if components[2] != "" {
+		xipStrings := strings.Split(components[2], ",")
+		s.xipList = make([]uint64, len(xipStrings))
+		for i, xipStr := range xipStrings {
+			s.xipList[i], err = strconv.ParseUint(xipStr, 10, 64)
+			if err != nil {
+				return fmt.Errorf("unable to parse xip: %s", xipStr)
+			}
+		}
+		slices.Sort(s.xipList)
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:49]: when would this not be sorted?

File: internal/datastore/postgres/snapshot.go [hunk 6]
```diff
@@ -0,0 +1,236 @@
...
+	} else {
+		s.xipList = nil
+	}
+
+	// Parsed successfully
+	s.status = pgtype.Present
+	return nil
+}
+
+// EncodeText should append the text format of self to buf. If self is the
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:59]: `self` -> `s.status`

File: internal/datastore/postgres/snapshot.go [hunk 7]
```diff
@@ -0,0 +1,236 @@
...
+const (
+	uncomparable comparisonResult = iota
+	equal
+	lt
+	gt
+	concurrent
+)
+
+func (s pgSnapshot) compare(rhs pgSnapshot) comparisonResult {
+	if s.status != pgtype.Present || rhs.status != pgtype.Present {
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:109]: this should definitely have documentation comments explaining the logic behind the comparison

File: internal/datastore/postgres/snapshot.go [hunk 8]
```diff
@@ -0,0 +1,236 @@
...
+		return uncomparable
+	}
+
+	var rhsHasMoreInfo bool
+	for _, txid := range append(s.xipList, s.xmax) {
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:114]: doesn't `append` modify the supplied slice if it has room? If so, could this cause problems?

File: internal/datastore/postgres/snapshot.go [hunk 9]
```diff
@@ -0,0 +1,236 @@
...
+	case rhsHasMoreInfo:
+		return lt
+	case lhsHasMoreInfo:
+		return gt
+	default:
+		return equal
+	}
+}
+
+func (s pgSnapshot) markComplete(txid uint64) pgSnapshot {
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:141]: doc comment on what this function does

File: internal/datastore/postgres/snapshot.go [hunk 10]
```diff
@@ -0,0 +1,236 @@
...
+		newSnapshot.xipList = newSnapshot.xipList[:startingXipLen-numToDrop]
+		if len(newSnapshot.xipList) == 0 {
+			newSnapshot.xipList = nil
+		}
+	}
+
+	return newSnapshot
+}
+
+func (s pgSnapshot) visible(txid uint64) bool {
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:226]: maybe `isTransactionVisible`?

File: internal/datastore/postgres/snapshot.go [hunk 11]
```diff
@@ -0,0 +1,236 @@
...
+	gt
+	concurrent
+)
+
+func (s pgSnapshot) compare(rhs pgSnapshot) comparisonResult {
+	if s.status != pgtype.Present || rhs.status != pgtype.Present {
+		return uncomparable
+	}
+
+	var rhsHasMoreInfo bool
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:113]: "has more info" seems kind of vague, but I don't really have a better name. Perhaps something like `rhsHasAdditionalTransactions`? not sure

File: proto/internal/impl/v1/pgrevision.proto [hunk 12]
```diff
@@ -0,0 +1,10 @@
+syntax = "proto3";
+package impl.v1;
+
+option go_package = "github.com/authzed/spicedb/pkg/proto/impl/v1";
+
+message PostgresRevision {
```
Comment (josephschorr) [inline proto/internal/impl/v1/pgrevision.proto:6]: doc comment

File: internal/datastore/postgres/postgres_test.go (hunk 2 above)
Comment (jakedt) [reply internal/datastore/postgres/postgres_test.go:222]: It actually changed back, and it's because we no longer need to keep around the stale transaction. This is essentially the reverse of this change:
https://github.com/authzed/spicedb/commit/fbaee5b00b34116ed1a14e6e0f8c27b2491d76cd

File: internal/datastore/postgres/snapshot.go (hunk 5 above)
Comment (jakedt) [reply internal/datastore/postgres/snapshot.go:49]: This is defensive, it should always be sorted.

File: internal/datastore/postgres/snapshot.go (hunk 10 above)
Comment (jakedt) [reply internal/datastore/postgres/snapshot.go:226]: Doesn't seem very idiomatic go to me.

File: internal/datastore/postgres/snapshot.go (hunk 8 above)
Comment (jakedt) [reply internal/datastore/postgres/snapshot.go:114]: I think this is safe: https://go.dev/play/p/CNqawJILr_6

File: internal/datastore/postgres/snapshot.go (hunk 11 above)
Comment (jakedt) [reply internal/datastore/postgres/snapshot.go:113]: Maybe it makes sense with the new comment?

File: internal/datastore/postgres/postgres.go [hunk 13]
```diff
@@ -59,11 +59,9 @@ const (
 
 	// The parameters to this format string are:
 	// 1: the created_xid or deleted_xid column name
-	// 2: the transaction table's snapshot column name
-	// 3: the transaction table name
-	// 4: the transaction table's xid column name
-	// 5: a squirrel library placeholder string, i.e. `?`
-	snapshotAlive = "pg_visible_in_snapshot(%[1]s, (SELECT %[2]s FROM %[3]s WHERE %[4]s = %[5]s)) = %[5]s"
+	// 2: a squirrel library placeholder string, i.e. `?`
```
Comment (josephschorr) [inline internal/datastore/postgres/postgres.go:62]: can we indicate what the placeholders are supposed to represent?

File: internal/datastore/postgres/revisions.go [hunk 14]
```diff
@@ -33,51 +32,63 @@ const (
...
 	//   %[3] Name of timestamp column
 	//   %[4] Inverse of GC window (in seconds)
+	//   %[5] Name of the snapshot column
 	queryValidTransaction = `
-	SELECT $1 >= (
-		SELECT %[1]s FROM %[2]s WHERE %[3]s >= NOW() - INTERVAL '%[4]f seconds' ORDER BY %[3]s ASC LIMIT 1
-	) as fresh, $1 > (
-		SELECT %[1]s FROM %[2]s ORDER BY %[3]s DESC LIMIT 1
-	) as unknown;`
+	WITH min AS (
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions.go:55]: maybe use a different CTE name than `min`, since at first glance I think its a keyword

File: internal/datastore/postgres/revisions_test.go [hunk 15]
```diff
@@ -4,69 +4,42 @@ import (
...
 	"testing"
 
-	"github.com/jackc/pgtype"
 	"github.com/stretchr/testify/require"
 )
 
-const (
-	maxInt = ^uint64(0) >> 1
-)
+// import (
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions_test.go:10]: remove?

File: internal/datastore/postgres/snapshot.go (hunk 11 above)
Comment (josephschorr) [reply internal/datastore/postgres/snapshot.go:126]: yeah, its fine

File: internal/datastore/postgres/snapshot.go (hunk 8 above)
Comment (josephschorr) [reply internal/datastore/postgres/snapshot.go:127]: Strange... https://pkg.go.dev/builtin#append says:

> The append built-in function appends elements to the end of a slice. If it has sufficient capacity, the destination is resliced to accommodate the new elements. If it does not, a new underlying array will be allocated. Append returns the updated slice. It is therefore necessary to store the result of append, often in the variable holding the slice itself:

Any ideas why it isn't returning the same slice?

File: internal/datastore/postgres/snapshot.go (hunk 10 above)
Comment (josephschorr) [reply internal/datastore/postgres/snapshot.go:247]: maybe `txvisible` then? to make it clear at the callsite its checking for a transaction?

File: internal/datastore/postgres/revisions_test.go (hunk 15 above)
Comment (jakedt) [reply internal/datastore/postgres/revisions_test.go:10]: wth?

File: internal/datastore/postgres/snapshot.go (hunk 8 above)
Comment (josephschorr) [reply internal/datastore/postgres/snapshot.go:127]: Hrmph... okay

**Comment by josephschorr** [comment]
@jakedt Please rebase at your convenience

File: internal/datastore/postgres/snapshot.go [hunk 16]
```diff
@@ -0,0 +1,257 @@
...
+		newSnapshot.xmin = newSnapshot.xipList[0]
+	} else {
+		newSnapshot.xmin = newSnapshot.xmax
+		newSnapshot.xipList = nil
+	}
+
+	return newSnapshot
+}
+
+// markComplete will create a new snapshot where the specified transaction will be marked as
```
Comment (josephschorr) [inline internal/datastore/postgres/snapshot.go:196]: `markInProgress`

File: internal/datastore/postgres/revisions.go [hunk 17]
```diff
@@ -151,6 +166,50 @@ func parseRevision(revisionStr string) (datastore.Revision, error) {
 	}, nil
 }
 
+func parseRevisionDecimal(revisionStr string) (datastore.Revision, error) {
+	components := strings.Split(revisionStr, ".")
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions.go:170]: add a comment documenting the "format" here, just for quick reference

File: internal/datastore/postgres/revisions.go [hunk 18]
```diff
@@ -151,6 +166,50 @@ func parseRevision(revisionStr string) (datastore.Revision, error) {
...
+	numComponents := len(components)
+	if numComponents != 1 && numComponents != 2 {
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions.go:172]: `< 1 || > 2`?

File: internal/datastore/postgres/revisions.go [hunk 19]
```diff
@@ -151,6 +166,50 @@ func parseRevision(revisionStr string) (datastore.Revision, error) {
...
+			fmt.Errorf("wrong number of components %d != 1 or 2", len(components)),
+		)
+	}
+
+	xid, err := strconv.ParseUint(components[0], 10, 64)
+	if err != nil {
+		return datastore.NoRevision, fmt.Errorf(errRevisionFormat, err)
+	}
+
+	xmax := xid + 1
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions.go:184]: why `+ 1`?

File: internal/datastore/postgres/revisions_test.go [hunk 20]
```diff
@@ -73,9 +74,103 @@ func TestRevisionSerDe(t *testing.T) {
...
+		{snap(maxInt+1, maxInt+1), "9223372036854775807", false},
+		{snap(maxInt-1, maxInt+1, maxInt-1), "9223372036854775807.9223372036854775806", false},
+		{snap(0, 0), "-500", true},
+	}
+
+	for _, tc := range testCases {
+		t.Run(tc.snapshot.String(), func(t *testing.T) {
+			require := require.New(t)
+
+			parsed, err := parseRevisionDecimal(tc.inputStr)
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions_test.go:104]: shouldn't this be testing the parseRevision overall?

edit: rename the test to TestRevisionParseOldRevisionFormat or somesuch

File: internal/datastore/postgres/revisions_test.go [hunk 21]
```diff
@@ -73,9 +74,103 @@ func TestRevisionSerDe(t *testing.T) {
...
 	}
 }
+
+func TestRevisionBackCompat(t *testing.T) {
+	testCases := []struct {
+		snapshot  pgSnapshot
+		inputStr  string
+		expectErr bool
+	}{
+		{snap(1, 1), "0", false},
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions_test.go:90]: add a few test cases:
- empty string
- random non-numeric values

File: internal/datastore/postgres/revisions.go [hunk 22]
```diff
@@ -120,7 +122,20 @@ func (pgd *pgDatastore) RevisionFromString(revisionStr string) (datastore.Revisi
 	return parseRevision(revisionStr)
 }
 
-func parseRevision(revisionStr string) (datastore.Revision, error) {
+func parseRevision(revisionStr string) (rev datastore.Revision, err error) {
```
[the remark this answers is not in the document]
Comment (jakedt) [reply internal/datastore/postgres/revisions.go:125]: The first version didn't have them. This turned out way more readable.

File: internal/datastore/postgres/revisions.go (hunk 19 above)
Comment (jakedt) [reply internal/datastore/postgres/revisions.go:184]: Explained in the doc comment.

**Comment by jakedt** [comment]
Updated

File: internal/datastore/postgres/revisions.go (hunk 22 above)
[the remark this answers is not in the document]
Comment (josephschorr) [reply internal/datastore/postgres/revisions.go:125]: Hrmph... okay

File: internal/datastore/postgres/revisions.go (hunk 18 above)
Comment (josephschorr) [reply internal/datastore/postgres/revisions.go:176]: I personally find it more readable at first glance

File: internal/datastore/postgres/revisions.go [hunk 23]
```diff
@@ -151,6 +166,54 @@ func parseRevision(revisionStr string) (datastore.Revision, error) {
 	}, nil
 }
 
+// parseRevisionDecimal parses a depricated decimal.Decimal encoding of the revision
```
Comment (josephschorr) [inline internal/datastore/postgres/revisions.go:169]: deprecated

**Review by josephschorr — APPROVED** [review]
LGTM
