### PR TITLE
Fix flake in Postgres GC revision test by ensuring GC is run

### LINKED ISSUE #1619: Flake: TestPostgresDatastore/postgres-16-head-/TestRevisionGC
```
=== RUN   TestPostgresDatastore/postgres-16-head-/TestRevisionGC
    revisions.go:166: 
        	Error Trace:	/Users/vroldanbet/git/spicedb/pkg/datastore/test/revisions.go:166
        	            				/Users/vroldanbet/git/spicedb/pkg/datastore/test/datastore.go:104
        	Error:      	An error is expected but got nil.
        	Test:       	TestPostgresDatastore/postgres-16-head-/TestRevisionGC
        	Messages:   	expected revision head-1 to be outside GC Window
        --- FAIL: TestPostgresDatastore/postgres-16-head-/TestRevisionGC (1.13s)
```

### PR DESCRIPTION
**Pull request by josephschorr**
Fixes #1619

### CODE REVIEW

File: internal/datastore/common/gc.go [hunk 1]
```diff
@@ -73,6 +73,10 @@ func RegisterGCMetrics() error {
 // GarbageCollector represents any datastore that supports external garbage
 // collection.
 type GarbageCollector interface {
+	HasGCRun() bool
+	MarkGCCompleted()
+	ResetGCCompleted()
```
Comment (vroldanbet) [inline internal/datastore/common/gc.go:78]: given this is only used in tests, can we perhaps extract it into its own interface. Then we can do type assertions in the test based on that interface. And the interface does not even need to be here, but closer to the consumer in the  test package using it

Comment (josephschorr) [reply internal/datastore/common/gc.go:78]: I prefer it being here to ensure that *all* GCable datastores are *forced* to implement it

Comment (vroldanbet) [reply internal/datastore/common/gc.go:78]: it can be forced if you make the test fail if the datastore does not implement the interface. Why making the API surface larger for something only used in a single test?

Comment (josephschorr) [reply internal/datastore/common/gc.go:78]: Because not all datastores implement the custom GC code

**Review by vroldanbet — APPROVED** [review]
